---
path_classifiers:
  docs:
    - blackbox/docs
  test:
    - blackbox/hdfs
    - blackbox/monitoring
    - blackbox/shared
    - blackbox/sqllogictest
  queries:
    - exclude: java/non-sync-override
  library:
    - es/upstream

extraction:
  python:
    python_setup:
      version: 3
  java:
    index:
      java_version: 11
